### ISSUE TITLE
Error when running Terraspace on modules using explicitly passed-on providers

### ISSUE THREAD

**Issue by syphernl** [boltops-tools/terraspace#151] opened 2021-11-15 14:42 UTC
## Checklist

- [X] Upgrade Terraspace: Are you using the latest version of Terraspace? This allows Terraspace to fix issues fast. There's an Upgrading Guide: https://terraspace.cloud/docs/misc/upgrading/
- [X] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [X] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System | `Ubuntu 21.10` |
| Terraform        |  `1.0.11`       |
| Terraspace       | `0.6.18`         |
| Ruby             |   `2.7.4p191`      |

---

## Problem Description

For certain tasks we need to do things in a different AWS region (e.g. `ACM`, `KMS` etc) than the one the main infrastructure is in. 
For instance: If one wants to use an `ACM` certificate with `CloudFront`, it needs to be present in the `us-east-1` region rather then the region the other account resources are in.

In vanilla Terraform (which also works with Terragrunt) we solved this by adding a secondary AWS Provider within the "global" region:

```hcl
# Primary provider for provisioning main infra
provider "aws" {
  region = "eu-west-1"

  assume_role {
      role_arn = "arn:aws:iam:XXXXXXXXXXXXX:role/ProvisionerRole"
   }
}

# Secondary provider for ACM / Route53
provider "aws" {
  region = "us-east-1"
  alias = "aws_global"

  assume_role {
      role_arn = "arn:aws:iam:XXXXXXXXXXXXX:role/ProvisionerRole"
   }
}
```

The module (called by the stack) passes along the appropriate provider like so:

```hcl
module "certificate" {
  source = "git::https://github.com/cloudposse/terraform-aws-acm-request-certificate.git?ref=0.15.1"
  providers = {
    aws = aws.aws_global
  }

  zone_name = "example.com"
  domain_name = "app.example.com"
}
```

This approach works fine with vanilla Terraform and with Terragrunt. However, doing so with TerraSpace results in receiving the following error:

```
│ Error: missing provider provider["registry.terraform.io/hashicorp/aws"].aws_global
```

## Step-by-step reproduction instructions

- See above

## Code Sample

- See above

**Comment by tongueroo** [comment] 2022-01-05 01:19
Unsure. Tried to reproduce it with this terraspace example project that 

* creates security groups 
* with different provider aliases
* on different AWS accounts
* using different roles to assume

Here's the repo: https://github.com/tongueroo/terraspace-multiple-providers

Here's also the debugging output:

<details>
 <summary>Click to Expand and See Debugging Session</summary>

    $ terraspace up demo -y
    Building .terraspace-cache/us-west-2/dev/stacks/demo
    Built in .terraspace-cache/us-west-2/dev/stacks/demo
    Current directory: .terraspace-cache/us-west-2/dev/stacks/demo
    => terraform plan -input=false -out /tmp/terraspace/plans/demo-5620d45a4deda68126b91aff6dc4e562.plan
    
    Terraform used the selected providers to generate the following execution
    plan. Resource actions are indicated with the following symbols:
      + create
    
    Terraform will perform the following actions:
      # random_pet.pet1 will be created
      + resource "random_pet" "pet1" {
          + id        = (known after apply)
          + length    = 2
          + separator = "-"
        }
      # random_pet.pet2 will be created
      + resource "random_pet" "pet2" {
          + id        = (known after apply)
          + length    = 2
          + separator = "-"
        }
      # module.sg1.aws_security_group.this will be created
      + resource "aws_security_group" "this" {
          + arn                    = (known after apply)
          + description            = (known after apply)
          + egress                 = (known after apply)
          + id                     = (known after apply)
          + ingress                = (known after apply)
          + name                   = (known after apply)
          + name_prefix            = (known after apply)
          + owner_id               = (known after apply)
          + revoke_rules_on_delete = false
          + tags_all               = (known after apply)
          + vpc_id                 = (known after apply)
        }
      # module.sg2.aws_security_group.this will be created
      + resource "aws_security_group" "this" {
          + arn                    = (known after apply)
          + description            = (known after apply)
          + egress                 = (known after apply)
          + id                     = (known after apply)
          + ingress                = (known after apply)
          + name                   = (known after apply)
          + name_prefix            = (known after apply)
          + owner_id               = (known after apply)
          + revoke_rules_on_delete = false
          + tags_all               = (known after apply)
          + vpc_id                 = (known after apply)
        }
    
    Plan: 4 to add, 0 to change, 0 to destroy.
    
    Changes to Outputs:
      + sg1_arn = (known after apply)
      + sg2_arn = (known after apply)
    
    ─────────────────────────────────────────────────────────────────────────────
    
    Saved the plan to: /tmp/terraspace/plans/demo-5620d45a4deda68126b91aff6dc4e562.plan
    
    To perform exactly these actions, run the following command to apply:
        terraform apply "/tmp/terraspace/plans/demo-5620d45a4deda68126b91aff6dc4e562.plan"
    => terraform apply -auto-approve -input=false /tmp/terraspace/plans/demo-5620d45a4deda68126b91aff6dc4e562.plan
    random_pet.pet1: Creating...
    random_pet.pet2: Creating...
    random_pet.pet1: Creation complete after 0s [id=notable-lobster]
    random_pet.pet2: Creation complete after 0s [id=sensible-seal]
    module.sg1.aws_security_group.this: Creating...
    module.sg2.aws_security_group.this: Creating...
    module.sg1.aws_security_group.this: Creation complete after 1s [id=sg-063c8fb1ab95ec2fe]
    module.sg2.aws_security_group.this: Creation complete after 3s [id=sg-04e5c4ed437502e2a]
    
    Apply complete! Resources: 4 added, 0 changed, 0 destroyed.
    
    
    Outputs:
    
    sg1_arn = "arn:aws:ec2:us-west-2:111111111111:security-group/sg-063c8fb1ab95ec2fe"
    sg2_arn = "arn:aws:ec2:us-east-1:222222222222:security-group/sg-04e5c4ed437502e2a"
    Time took: 7s
    $
</details>

It just deploys 2 security groups. Each one using a different provider and different region. It outputs the security ARN so can easily debug and confirm that they are being created in different regions/accounts.

```
    Outputs:
    
    sg1_arn = "arn:aws:ec2:us-west-2:111111111111:security-group/sg-063c8fb1ab95ec2fe"
    sg2_arn = "arn:aws:ec2:us-east-1:222222222222:security-group/sg-04e5c4ed437502e2a"
```

Confirmed that it does.

You've provided a lot of info, but still unable to reproduce. Maybe an example repo would help. Closing this out. Feel free to provide more info though if you find more clues.

Also, consider trying:

    terraspace build demo
    cd .terraspace-cache/us-west-2/dev/stacks/demo
    terraform init
    terraform apply

That's pretty much what terraspace does. https://terraspace.cloud/docs/intro/how-terraspace-works/

So if you can get it working with plain terraform, it should in theory work with terraspace.

Note: The `.terraspace-cache` folder will use whatever your `AWS_REGION` is set to. Or if that is not set, it'll try to get it from your `~/.aws/config`, and then default to `us-east-1`. Generally speaking, that's what happens. Here's the lookup logic: https://github.com/boltops-tools/aws_data/blob/master/lib/aws_data.rb

**Closed by tongueroo** 2022-01-05 01:19 UTC
Labels: bug, help wanted
